// AutoSvr.idl : IDL source for AutoSvr
//

// This file will be processed by the MIDL tool to
// produce the type library (AutoSvr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[ object, uuid(B89677AD-4C07-4CF8-96E2-366FD3E9497F), dual, nonextensible, pointer_default(unique) ]
interface ISvcControl : IDispatch
{
	HRESULT DoStartSvc([in] LPCWSTR szSvcName, [out, retval] BSTR *result);
	HRESULT DoStopSvc([in] LPCWSTR szSvcName, [out, retval] BSTR *result);
};

[ uuid(8AC91E1C-9176-4902-AB5A-DD67AEFD508D), version(1.0) ]
library AutoSvrLib
{
	importlib("stdole2.tlb");
	[
		uuid(CCE632FB-6FEB-497C-BD71-74E99DE8447E)		
	]
	coclass SvcControlComponent
	{
		[default] interface ISvcControl;
	};
};

